# https://w7.pngwing.com/pngs/956/695/png-transparent-mongodb-original-wordmark-logo-icon-thumbnail.png
version: "3"
x-omnistrate-my-account:
  AwsAccountId: '<YOUR AWS ACCOUNT ID>'
  AwsBootstrapRoleAccountArn: '<ROLE FROM THE ACCOUNT SETUP>'
  GcpProjectId: '<YOUR GCP PROJECT ID>'
  GcpProjectNumber: '<YOUR GCP PROJECT NUMBER>'
  GcpServiceAccountEmail: '<YOUR GCP BOOTSTRAP SERVICE ACCOUNT EMAIL>'
x-omnistrate-integrations:
  - omnistrateLogging
  - omnistrateMetrics
services:
  mongodb:
    x-omnistrate-mode-internal: false
    image: docker.io/omnistrate/mongodb:6.0-3
    ports:
      - 27017:27017
    environment:
      - SECURITY_CONTEXT_USER_ID=999
      - SECURITY_CONTEXT_GROUP_ID=999
      - SECURITY_CONTEXT_FS_GROUP=999
      - MONGO_INITDB_ROOT_USERNAME=$var.mongodbUsername
      - MONGO_INITDB_ROOT_PASSWORD=$var.mongodbPassword
      - REPLICA_SET_KEY=$var.mongodbReplicaSetKey
      - REPLICA_SET_NAME=$var.mongodbReplicaSetName
    x-omnistrate-actionhooks:
      - scope: CLUSTER
        type: INIT
        commandTemplate: |
          mongosh "mongodb://{{ $var.mongodbUsername }}:{{ $var.mongodbPassword }}@{{ $sys.compute.nodes[0].name }}:27017/?authMechanism=DEFAULT" --eval "rs.initiate()"
      - scope: NODE
        type: ADD
        commandTemplate: |
          #!/bin/bash
          set -ex

          # Check if NODE_NAME is not equal to 'mongodb-0'
          if [ "$NODE_NAME" != {{ $sys.compute.nodes[0].name }} ]; then
              # Run the mongosh command
              mongosh "mongodb://{{ $var.mongodbUsername }}:{{ $var.mongodbPassword }}@{{ $sys.compute.nodes[0].name }}:27017/?authMechanism=DEFAULT" --eval "rs.add( { host: '{{ $sys.compute.node.name }}' } )"
          fi
      - scope: NODE
        type: REMOVE
        commandTemplate: |
          #!/bin/bash

          set -ex

          # Check if NODE_NAME is not equal to 'mongodb-0'
          if [ "$NODE_NAME" != {{ $sys.compute.nodes[0].name }} ]; then
              # Run the mongosh command
              mongosh "mongodb://{{ $var.mongodbUsername }}:{{ $var.mongodbPassword }}@{{ $sys.compute.nodes[0].name }}:27017/?authMechanism=DEFAULT" --eval "rs.remove('{{ $sys.compute.node.name }}')"
          fi
    x-omnistrate-compute:
      replicaCountAPIParam: numReplicas
      instanceTypes:
        - cloudProvider: aws
          apiParam: instanceType
        - cloudProvider: gcp
          apiParam: instanceType
    x-omnistrate-capabilities:
      enableMultiZone: true
      enableEndpointPerReplica: true
    volumes:
      - source: ./mongodb_master_data
        target: /data/db
        type: bind
        x-omnistrate-storage:
          aws:
            instanceStorageType: AWS::EBS_GP3
            instanceStorageSizeGi: 100
            instanceStorageIOPSAPIParam: instanceStorageIOPS
            instanceStorageThroughputAPIParam: instanceStorageThroughput
          gcp:
            instanceStorageType: GCP::PD_BALANCED
            instanceStorageSizeGi: 100
    x-omnistrate-api-params:
      - key: instanceType
        description: Instance Type
        name: Instance Type
        type: String
        modifiable: true
        required: true
        export: true
      - key: mongodbPassword
        description: Default DB Password
        name: Password
        type: String
        modifiable: false
        required: true
        export: false
      - key: mongodbUsername
        description: Default DB Username
        name: Username
        type: String
        modifiable: false
        required: true
        export: true
      - key: mongodbReplicaSetKey
        description: Replica Set Key
        name: Replica Set Key
        type: String
        modifiable: false
        required: true
        export: true
      - key: mongodbReplicaSetName
        description: Replica Set Name
        name: Replica Set Name
        type: String
        modifiable: false
        required: true
        export: true
      - key: instanceStorageIOPS
        description: Instance Storage IOPS; Applicable to AWS only
        name: Instance Storage IOPS
        type: Float64
        modifiable: true
        required: true
        export: true
      - key: instanceStorageThroughput
        description: Instance Storage Throughput (in MB /s); Applicable to AWS only
        name: Instance Storage Throughput
        type: Float64
        modifiable: true
        required: true
        export: true
      - key: numReplicas
        description: Number of Replicas
        name: Number of Replicas
        type: Float64
        modifiable: true
        required: true
        export: true

